import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { Payload } from "../src/payload.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Load the fixtures generated by `pnpm ledger:gen-fixtures`. */
function loadFixtures(): unknown[] {
	const path = join(__dirname, "..", "fixtures", "payload-variants.json");
	return JSON.parse(readFileSync(path, "utf8"));
}

/** Exhaustive switch: adding a new Rust variant without a TS case here produces
 * a TypeScript compile error at `never`.
 */
function kindName(p: Payload): string {
	const keys = Object.keys(p as object);
	if (keys.length !== 1) {
		throw new Error(`expected exactly one variant key, got ${keys.length}`);
	}
	const k = keys[0];
	switch (k) {
		case "RunStartedV1":
		case "RunCompletedV1":
		case "RunFailedV1":
		case "UnitStartedV1":
		case "UnitCompletedV1":
		case "UnitFailedV1":
		case "UnitCancelledV1":
		case "GitCheckpointV1":
		case "ModelRequestV1":
		case "ModelResponseV1":
		case "ToolRequestStoredV1":
		case "ToolResultV1":
		case "WorkspaceReadV1":
		case "WorkspaceWriteV1":
			return k;
		default: {
			const _exhaustive: never = k as never;
			throw new Error(`unknown variant ${_exhaustive}`);
		}
	}
}

describe("payload drift alarm", () => {
	it("every fixture parses as a known variant", () => {
		const fixtures = loadFixtures();
		expect(fixtures.length).toBe(14);
		for (const fx of fixtures) {
			const name = kindName(fx as Payload);
			expect(typeof name).toBe("string");
		}
	});
});
