import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
	EventKind,
	RunAdmissionDecision,
	type RunAdmissionRecordedV1,
} from "../src/generated/index.js";
import type { Payload } from "../src/payload.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** The externally-tagged variant keys of the `Payload` union. A bare
 * `keyof Payload` intersects the members' keys down to `never` because each
 * union member is a single-key object; distributing `keyof` over each member
 * (via the naked type parameter `T`, which is what makes the conditional
 * distributive) instead yields the union of all 23 variant names. */
type KeysOfUnion<T> = T extends unknown ? keyof T : never;
type PayloadKey = KeysOfUnion<Payload>;

/** Compile-time exhaustiveness gate over the `Payload` union.
 *
 * `satisfies Record<PayloadKey, true>` forces this table to list every
 * `Payload` variant key and *only* those keys:
 *  - add a Rust variant (→ a new `Payload` member) without an entry here and
 *    tsc fails with "Property '…' is missing … in type Record<PayloadKey, true>";
 *  - remove or rename a variant and the now-orphaned key fails to compile as an
 *    excess property.
 *
 * This replaces the previous `Object.keys(p)`→`switch`→`never` check, which was
 * inert: `Object.keys` widens to `string[]` and the `k as never` cast erased the
 * type, so a missing case never produced a compile error. */
const KNOWN_VARIANT_KEYS = {
	RunStartedV1: true,
	RunCompletedV1: true,
	RunFailedV1: true,
	ResultReadyV1: true,
	RunAdmissionRecordedV1: true,
	PlanAdmittedV1: true,
	PlanReceiptRecordedV1: true,
	ActivityStartedV1: true,
	ActivityCompletedV1: true,
	UnitStartedV1: true,
	UnitCompletedV1: true,
	UnitFailedV1: true,
	UnitCancelledV1: true,
	GitCheckpointV1: true,
	ModelRequestV1: true,
	ModelResponseV1: true,
	ToolRequestStoredV1: true,
	ToolResultV1: true,
	WorkspaceReadV1: true,
	WorkspaceWriteV1: true,
	TapeCheckpointV1: true,
	CapabilityDeniedV1: true,
	AcceptanceRecordedV1: true,
	OperatorDecisionRecordedV1: true,
} satisfies Record<PayloadKey, true>;

/** Runtime view of the compile-checked table, so the drift alarm below is
 * driven by the same exhaustive set rather than a second hand-kept list. */
const KNOWN_KEYS = new Set<string>(Object.keys(KNOWN_VARIANT_KEYS));

/** Load the fixtures generated by `pnpm ledger:gen-fixtures`. */
function loadFixtures(): unknown[] {
	const path = join(__dirname, "..", "fixtures", "payload-variants.json");
	return JSON.parse(readFileSync(path, "utf8"));
}

/** The single externally-tagged key of a payload fixture, checked against the
 * known-variant set at runtime. A Rust variant with no TS entry throws here —
 * the runtime half of the drift alarm (the compile half is `KNOWN_VARIANT_KEYS`). */
function kindName(p: Payload): PayloadKey {
	const keys = Object.keys(p as object);
	if (keys.length !== 1) {
		throw new Error(`expected exactly one variant key, got ${keys.length}`);
	}
	const k = keys[0];
	if (!KNOWN_KEYS.has(k)) {
		throw new Error(`unknown payload variant: ${k}`);
	}
	return k as PayloadKey;
}

describe("payload drift alarm", () => {
	it("every fixture parses as a known variant", () => {
		const fixtures = loadFixtures();
		expect(KNOWN_KEYS.size).toBe(24);
		expect(fixtures.length).toBe(KNOWN_KEYS.size);
		const names: string[] = [];
		for (const fx of fixtures) {
			const name = kindName(fx as Payload);
			names.push(name);
			expect(typeof name).toBe("string");
		}
		expect(names).toContain("RunAdmissionRecordedV1");
		expect(names).toContain("TapeCheckpointV1");
		expect(names).toContain("PlanAdmittedV1");
		expect(names).toContain("PlanReceiptRecordedV1");
		expect(names).toContain("ActivityStartedV1");
		expect(names).toContain("ActivityCompletedV1");
		expect(EventKind.PlanAdmitted).toBe("plan_admitted");
		expect(EventKind.PlanReceiptRecorded).toBe("plan_receipt");
		expect(EventKind.ActivityCompleted).toBe("activity_completed");
		expect(EventKind.CapabilityDenied).toBe("capability_denied");
		expect(EventKind.AcceptanceRecorded).toBe("acceptance_recorded");
		expect(names).toContain("OperatorDecisionRecordedV1");
		expect(EventKind.OperatorDecisionRecorded).toBe(
			"operator_decision_recorded",
		);
	});

	it("run admission fixture matches the generated wire contract", () => {
		const fixtures = loadFixtures();
		const admission = fixtures.find(
			(fx): fx is { RunAdmissionRecordedV1: RunAdmissionRecordedV1 } =>
				typeof fx === "object" && fx !== null && "RunAdmissionRecordedV1" in fx,
		);

		expect(EventKind.RunAdmissionRecorded).toBe("run_admission_recorded");
		expect(admission).toBeDefined();
		const payload = admission?.RunAdmissionRecordedV1;
		expect(payload?.decision).toBe(RunAdmissionDecision.Pass);
		expect(payload?.will_execute_worker).toBe(true);
		expect(payload?.receipt_ref).toBe("cas:sha256:aa");
		expect(payload?.evidence_inputs[0]?.digest).toBe("sha256:bb");
		expect(Object.hasOwn(payload?.evidence_inputs[0] ?? {}, "reason")).toBe(
			false,
		);
	});
});
